apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-camel-cluster-singleton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-camel-cluster-singleton

  template:
    metadata:
      labels:
        app: spring-camel-cluster-singleton

    spec:
      containers:
        - name: spring-camel-cluster-singleton
          image: app-image
      serviceAccountName: "spring-camel-cluster-singleton"